---

- name: setup the basic environment
  hosts: "{{ node_setup_group | default('nodes_setup') }}"
  tasks:
    - import_tasks: "{{ setup_tasks | default('../app/_setup.yml') }}"
      vars:
        work_dir: "{{ lookup('env', 'PWD') }}"
